### ISSUE TITLE
Automatic compilation

### ISSUE THREAD

**Issue by hmsjy2017** [ryanfortner/gitea-debs#1]
I think I can try to use GitHub Actions to automatically compile. I found a script here: https://packages.azlux.fr/scripts/gitea.txt
In addition, VSCodium's package repository provides a good example. Whenever VSCodium releases a new version, GitLab Runner automatically adds the package to the repository and signs it. https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/blob/master/updaterepos.sh

**Comment by ryanfortner** [comment]
I'm currently using my pi 4 for automatic build, it checks for a new release every 24 hours. The script I use is based on Azlux's, but GitHub actions would probably work better. 

Thanks for letting me know about the VSCodium script! That will be helpful

**Comment by hmsjy2017** [comment]
@chunky-milk I think you can use the Raspberry Pi as a self-hosted GitHub runner or directly use the runner provided by GitHub.

**Comment by hmsjy2017** [comment]
@chunky-milk Travis CI already supports building on the arm64 architecture. I think it might be a good choice to use Travis CI to compile software that supports Raspberry Pi.
https://docs.travis-ci.com/user/multi-cpu-architectures/

**Comment by ryanfortner** [comment]
Closing this issue now, as automatic builds for Gitea are now in Raspbian Addons
